thisdot/tech-community-slacks

README.md
Hi Tracy, can you see if you like the format of the list? I haven't included other non-local slack channels with this list. If you want I can add those on at the bottom of the list. Please let me know. Thanks!
=> List of local slack channels

README.md
I think I saw this repo in Twitter or something.  Good stuff!  Added one that I know about
=> Add yvrdev slack

README.md
Alsace - GeekDpt in Strasbourg (but not limited to the region)
=> Added country France and GeekDpt

README.md
Small typo and adding my Slack. We are based out of Wroclaw and open to discussing anything related to our city.
@ladyleet not sure it fits here :)
=> Add Callstack OSS

README.md
=> Add Elsass-dev

README.md
=> Add 757 Dev to list for Virginia 

README.md
We use Discord for community chat, but since Reactiflux is in here as well, I guess it should be included :)
=> Add Vue chat

README.md
Added the http://baltimoretech.org/ slack
=> Added Baltimore Tech

README.md
Add channels for NEPA Tech/NEPA.js and the Wilkes-Barre Community; split PA by region for ease of reading.
EDIT: Thank you for this resource!
=> Add channels from Northeast Pennsylvania

README.md
[meant to take over where #28 left off]
Also updated heading hierarchy to not jump levels (h1 to h3).
I'll keep this fork up to date with your master, to make it easy when you're ready to pull this.
=> Use Markdown instead of HTML

README.md
=> Update DevChat link

README.md
The most quality community in Vietnam. Not only about Ruby but also JS, Elixir, DevOps...
=> Add Ruby Vietnam's Slack

README.md
Added GDG Baroda's official Slack group invite link. #38
=> Add GDG Baroda Slack link

README.md
Link to the singup for the az-webdevs slack channel
=> add Arizona

README.md
=> Btw, vueslack is still alive

README.md
corrects many deprecated links
=> update list of invite URLs

README.md
Updated many links to reflect invite pages. Also removed the duplicate section for India.
=> Update links to invites

README.md
added SecDSM and DSMWebGeeks and SecKC; Slacks and Websites; added CIALUG slack.
=> added midwest groups

README.md
Added NWA Dev Slack group for Arkansas
=> Add NWA Dev Slack group for AR

README.md
=> added official slack group of GDG Bangalore

README.md
Add entry for Irish Tech Community slack.
=> Add Ireland - Irish Tech Community

README.md
=> Added BlrDroid Bangalore by dhanush13-c

README.md
=> added openEBS Bangalore by dhanush13-c

README.md
=> Dhanush13c

README.md
Hi there, I add some italian Slack channels to this useful repo. :100: 
#38
=> README updated with some italian Slack channels.

README.md
Add the site which has an active slack channel
=> Add Louisville.io to group

README.md
=> added firebase

README.md
re-arranged channels in alphabetical order; removed redundant listings
=> cleaned up Iowa list

README.md
=> Update PWAs Slack link

README.md
Adding emojis so we can make a bit more friendly and colourful. Hope you like it!
=> Adding emoji flags

README.md
Added SWFL meetup's slack channel. We discuss anything and everything related to technology :)
=> Added South West Florida meetup group slack channel

README.md
Added sites for Front End Developers of Miami and Wynwood Tech communities.
=> Added FEDM and Wynwood Tech Slacks to Florida

README.md
Added JS, Java, Rust, Connected data communities from Rome.
=> Update README with Rome local communities

README.md
Added an entry for Code D'Ivoire a developer community in Ivory Coast
=> Added entries for Cote d'Ivoire

README.md
Added MSPTEch, TC Chaos Engineering Community, Modern Agile, A/B Testing, Ministry of Testing, and Testers.io slack
=> Added MN and Testing slacks

README.md
Hi,
I propose to add NantesJS slack link 🙏(This is the invite link)
Thank you in advance
=> Add NantesJS slack link

README.md
Adding [jsheroes](https://jsheroes.io) slack community
=> docs: add jsheroes slack community

README.md
Adding the slack community of the Node.js Security WG to this awesome list
=> docs: add nodejs security wg slack channel

README.md
Invite link: https://holodevelopersslack.azurewebsites.net/ 
2k+ registered members
A good resource for HoloLens and Mixed Reality
=> Added a HoloLens related slack group: Holo Developers

README.md
https://mke-slack.herokuapp.com/, https://milwaukee.slack.com 
Currently 1,534 members
=> Add Milwaukee Slack

README.md
Added JS Belgrade community slack 🎉🇷🇸
https://github.com/ladyleet/tech-community-slacks/issues/38
=> JS Belgrade community slack

README.md
Adding our lovely small developer community.
=> Add Turku <3 Frontend community

README.md
Added header for MO stating there are several groups and reordered in alpha.
=> Add SGF Web Devs for Springfield, MO

README.md
Charlotte Devs is a large and active Slack Group of +1,000 members. Very newbie friendly and helpful.
=> Add Charlotte Devs to NC

README.md
Add mobile platform Community into the Community groups.
=> Add mobile community group from all over the world

README.md
Updated Slack information for Australian and New Zealand developer Slack group
=> Added DEVANZ

README.md
Adding a new Security section and the Node.js Security WG slack channel
=> doc: new security section for node.js security wg

README.md
Add a couple of additional popular regional Slack groups.
=> Add New Mexico and an additional LA Slack Group

README.md
Highly active developer/tech slack based out of wichita, ks that has over 900 members.
=> Add Wichita, Kansas Developer/Tech Slack devICT

README.md
I've added the Slack communities I'm part of.
=> Add WeAllJS, CodeBuddies & CodeNewbie

README.md
Add the slack channel for the secure developer community
Reference: https://thesecuredeveloper.com
=> docs(security): add the secure developer community

README.md
Added Training Center and BrazilJS and fix grammatical errors
=> Added communities

README.md
Adds two dev groups in Chattanooga, one in TriCities. 
Cleaned up the formatting to mirror other states with multiple entries.
=> Add chadev, devanooga, and tridev

README.md
I want to be contributing tech-slack communities in Nigeria
=> Nigeria update on tech-slack communities for merge

README.md
- added Germany to the list of countries
- added ReactJS.DE to Germany
=> Add Germany to the list with ReactJS.DE

README.md
- Adding **Angular Chile**
- Adding **devsChile**
- Adding **Noders**
=> Adding Chilean Communities 🇨🇱

README.md
Add to Virginia List:
* Rocktown Tech - Harrisonburg and surrounding communities
* Cville - Charlottesville Area
=> Add to Virginia Slack List

README.md
Add Chilean, Argentinian community for dev
=> Add community for dev

README.md
=> community duplicate in README

README.md
=> Add AWS Italy

README.md
This adds http://www.phackers.com/
=> Add Philippines

README.md
This is PR for Indonesia Tech Slack Community
=> Add Indonesia Slack Community

README.md
Hey 👋 
Awesome repo! I've added the meetup I organize - [LeicesterJS](https://leicesterjs.org/) to the mix 👍 
Thanks a lot!
=> Added LeicesterJS 🦊

README.md
- Added the relevant city name to each group
- Alphabetized the groups by city name
- Cleaned up the spacing and formatting
- Checked for old/broken links to remove and update
=> Update Southeast Formatting

README.md
Hey, this is an awesome list!
I’d like to recommend the addition of [Community Chat](https://comm.chat) to this list. It’s a private community of community builders and community managers (including DevRel managers!). A great place to receive personal advice and support people need to advance as a community leader.
This would be an awesome additional resource for this list 👍
=> Update README.md - Additional Community Group

README.md
=> Add Hawaii Slack

README.md
JDHH (https://www.meetup.com/Junior-Developer-Happy-Hour/) community uses this Slack to communicate. Currently, you must be invited by someone already in the community. Invite links are also given out at every JDHH meetup.
=> Add Developer Army Slack

README.md
Adds an entry for DevEdmonton, in Edmonton, Alberta, Canada.
=> adds DevEdmonton entry to Canada list

README.md
=> Add Canada: victoria, halifax groups. Add Denmark slack groups

README.md
- [ KaggleNYC] Name of Slack group is present
- [ LInk is broken] Reason for requesting removal is present
closes #255
=> chore: removing kagglenyc from readme.md

README.md
Added CTO Craft and CTO Craft Con
=> Adding CTO Craft and CTO Craft Con 

README.md
=> add Jina AI Slack link and introduction

README.md
=> add Colorado-Security and TechYeet

README.md
=> Added slack channel link to the Nigeria category

README.md
=> Fixing some formatting

README.md
=> Add Symfony and a Canada (calgary) slack

README.md
=> Add Denver Tech Talk to CO

README.md
=> docs: adding entry for Spain tech group

README.md
Reason: cracking down on non-STL solicitations
=> Removing USA/STL

README.md
=> New URL for our Slack front door.

README.md
=> Add HackGreenville to README

README.md
=> Adding open source Falco to the list of security projects

README.md
=> Add Toulouse tech link

README.md
=> Update README.md to add the Drupal project.

README.md
I added some links to some IL and MN based slacks and fixed some broken links
=> Added some IL and MN based slacks
