README.md

Thanks for doing this @ladyleet !!
Reactiflux used to be on Slack but we got too big and had to leave. We are on discord now. So is Reason's community (https://discordapp.com/invite/reasonml).
I know this is a list of slack channel's... any chance we can still be added to the list?

Adding Reactiflux & ReasonML (Discord Channels)

---

README.md

- Add popular Slack channels like GDG Pune, GDG Ahmedabad, mindorks.
- Reformate section of India based channels.
Fixes: #36

Add India based Slack channels.

---

README.md

IndyHackers updated with invitation URL. Invitation service is hosted on separate Heroku URL.

IndyHackers updated with invitation URL

---

README.md

- Edit Women in Tech (WITchat) slack sign-up link
- Add MongoDB slack to Technologies
- Add Ladies of WordPress slack to Women
- Add Dev Evangelist slack to Community Groups

Edit link and add new slacks to list

---

README.md

Added RennesJS Slack group for Rennes, France. #38

Add RennesJS Slack link

---

README.md

Fix typo and added link to slack channel for community since it's not currently shown directly on the site

Typo & Slack Link

---

README.md

Hi there, this fix realigns the Italy section in the proper alphabetically location (i.e.: after Ireland).

Italy section alphabetically realigned

---

README.md

We've seen a huge increase in the amount of spam in our slack since getting added to this list and would like to be removed.

remove 757dev slack

---

README.md

This commit adds the slack URL for the 757 (Hampton Roads) dev group.

Add Hampton Roads 757dev

---

README.md

Lousiville meetup had a space between the `]` and `(` that caused the Markdown link to not be parsed as such.

removed space to fix Markdown formatting break

---

README.md

Added CodeBuddies: a global community of code learners who help each other through conversations on Slack and peer-to-peer organized study groups and virtual hangouts.
This project is free, not-for-profit, transparent on Open Collective,  open-sourced, and powered by a fantastic team of core volunteer contributors.

Add the CodeBuddies Slack to `General Dev`

---

README.md

Add Montpellier tech community slack and link for invitation.

France - Add Montpellier tech community slack

---

README.md

This changes the address of the link for the STL Tech slack to point to our landing page instead of the invite app.

fix STL Tech Slack link

---

README.md

Add LA Devs, a new community for developers in Southern CA.

Add LA Devs

---

README.md

This PR adds in a couple of the 🇳🇿 New Zealand Slack communities: JSNZ and Develop NZ.

Add New Zealand communities

---

README.md

256 is the area code for Huntsville and surrounding areas, hence
the name.
Also fix some trailing whitespace in TN.

Add tech256 for North Alabama

---

README.md

Added the slack workspace of the Open Seattle org.
Details (including sign-up link): https://openseattle.org/slack/

add Open Seattle for Washington

---

README.md

For some reason the `Security` category exists twice:
1. with `Node.js Security WG` and `The Secure Developer`
2. with only `Node.js Security WG`
I removed the duplicate version.

Remove duplicate `Security` category

---

README.md

Great tech community in New Haven, CT with a very popular Slack group. All are welcome!

Add NewHaven.io

---

README.md

New UK Slack workspace added for LeedsDevs - all devs and tech professionals in the Leeds/Yorkshire area are welcome.

added LeedsDevs (UK)

---

README.md

This PR:
* adds Developers Italia to the Italian Slack communities list.
@ladyleet, thanks!

Add Developers Italia to Italy

---

README.md

I added the tampa devs slack group a few months ago, but im not seeing the listing again on the readme. This is another PR to add it back in:
Previous PR for reference:
https://github.com/thisdot/tech-community-slacks/pull/240

Add Tampa Devs (again?)

---

README.md

adding slack channel to public slack communities of kubecon which is about cloud native technologies

Add kubecon to the Conferences

---

README.md

Denver Devs is shutting down (deleting their discord) today: https://denverdevs.org/

Remove Denver Devs (defunct)

---

README.md

* The link to join the Triangle Developer's Slack has been updated since Heroku deprecated their hobby-tier instances

Fix link to Traingle Developers Slack

---

README.md

Torontojs is now pointing to the website, where people can join slack.
I also removed a bunch of links from the Canada section. All of them are dead links. Also tried some variants and googling.
- [X ] Suggestion is not a duplicate
- [ X] Suggestion is placed in the proper country according the slack channel’s demographic or if it’s a general channel, it’s placed in the appropriate category
- [X ] Brief description of the channel is accurate and properly typed
- [X ] Name of Slack group is present
- [ X] Reason for requesting removal is present

Update toronto links

---

README.md

We're a local group and we've been getting too many remote members joining from this list. We'd like to remove ourselves.
I'm one of the admins over there, and you can find me on the group's about page (https://newhaven.io/about/).
I appreciate what y'all are doing, but we just don't need to be on this list anymore.

Removing New Haven IO from the list.
